# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: E-MIND Lab # the website title (if blank, full name will be used instead)
first_name: Eunju
middle_name:
last_name: Jeong
email: ejeong@ewha.ac.kr
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Ewha Music Intelligence Neuroscience Design Lab - 
  Bridging Music Therapy, Neuroscience, and Digital Healthcare
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords: music therapy, neuroscience, digital healthcare, HCI, EEG, neurorehabilitation, soundscape
lang: en # the language of your site (for example: en, fr, cn, ru)
icon: ☍ # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://eMIND-lab.github.io # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: true # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer, use the same path as permalink for a page, helps to conform with EU GDPR

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# repo color theme
repo_theme_light: default # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md

# Specify which pages you want to appear in the navigation bar.
nav_order:
  - about         # Homepage
  - people        # People
  - projects      # Projects
  - publications  # Publications
  - news          # News

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization

rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: false

# Dimensions
max_width: 800px

# TODO: add layout settings (hierarchical prefix defined defineddings defined defined)

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

# Display Open Graph in the HTML head of your site for social media previews
# Display links to the page with an pointimage preview
serve_og_meta: false # Include Open Graph meta tags in the HTML head
serve_schema_org: false # Include Schema.org in the HTML head
og_image: # The site-wide (default for all links) parsing Open Graph preview image

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: eMIND-lab
gitlab_username: # your GitLab user name
x_username: # your X handle
mastodon_username: # your mastodon instance+username in the format: <instance.tld>/@<username>
linkedin_username: eunju-jeong-b8b46517
telegram_username: # your Telegram user name
scholar_userid: uDnyV4sAAAAJ
semanticscholar_id: # your Semantic Scholar ID
research_gate_profile: Eunju-Jeong-2
orcid_id: 0000-0002-5064-5419
medium_username: # your Medium user name
quora_username: # your Quora user name
publons_id: # your ID on Publons
lattes_id: # your ID on Lattes (Brazilian Curriculum Vitae)
osf_id: # your OSF ID
wikidata_id: # your wikidata id

contact_note: >
  Department of Music Therapy, Graduate School, Ewha Womans University, Seoul, Republic of Korea

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics: # your Google Analytics measurement ID (format: G-XXXXXXXXXX)
cronitor_analytics: # cronitor RUM analytics site ID (format: XXXXXXXXX)

google_site_verification: # your google-site-verification ID (Google Search Console)
bing_site_verification: # out of bing-site-verification ID (Bing Webmaster)

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: E-MIND Lab News # blog_name will be displayed in your blog page
blog_nav_title: News # your blog page title (default: blog)
blog_description: Latest news and updates from E-MIND Lab
permalink: /blog/:year/:title/

# Pagination
pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

announcements:
  enabled: true
  scrollable: true # adds a vertical scroll bar if there are more than 3 news items
  limit: 5 # leave blank to include all the news in the `_news` folder

latest_posts:
  enabled: false
  scrollable: true # adds a vertical scroll bar if there are more than 3 new posts items
  limit: 3 # leave blank to include all the blog posts

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and samples
markdown: kramdown
highlighter: rouge

# Includes & Excludes
include: ["_pages"]
exclude:
  - bin/
  - Gemfile
  - Gemfile.lock
  - vendor

# Plug-ins
plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Jeong]
  first_name: [Eunju, E.]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics: false
enable_cronitor_analytics: false
enable_google_verification: false
enable_bing_verification: false
enable_masonry: true
enable_math: false
enable_tooltips: false
enable_darkmode: true
enable_navbar_social: false
enable_project_categories: true
enable_medium_zoom: true

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

bootstrap-table:
  version: "1.22.1"
datatables:
  version: "1.13.6"
  extensions:
    buttons:
      version: "2.4.1"
altmetric_badge:
  version: "4"
d3:
  version: "7"
  integrity: "sha256-WBoAHnT0C7rwCPwnAlNLPUTUkvB2RPSY0DIz0wdi/VY="
highlightjs:
  version: "11.9.0"
  integrity:
    css:
      light: "sha256-Oppd74ucMR5a5Dq96FxjEzGF7tTw2Foc8lbEip5anSs="
      dark: "sha256-nyCNAiECe2GAFJuJmIA5bEgXyGAjpvUQMRun6d6lL4c="
    js: "sha256-g+B7WxhfqfhHIl4IpGb0h3GnCJECDOL8vm63MBjjMSQ="
chartjs:
  version: "4.4.1"
  integrity: "sha256-C+pkFT3cBTB4kCsGGPm3pVQVmp+xiRXGKlw20sXdFWE="
  chartjs_adapter_date_fns:
    version: "3.0.0"
    integrity: "sha256-Fb17U+Zk5MZ6R+8mFhHUhm9nS3sVFnh0JzEaxfmibY="
  date_fns:
    version: "2.30.0"
    integrity: "sha256-TW9wPdnifNlXI+XpDB1MBxVYfZG3F6bOZcjDjfMYdyk="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
leaflet:
  version: "1.9.4"
  integrity:
    css: "sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
    js: "sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
mathjax:
  version: "3.2.0"
masonry:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.20.0"
  integrity:
    css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
    js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
medium_zoom:
  version: "1.0.8"
  integrity: "sha256-7PhEpEWnCrlMRYkBrJxO16O0aFNu4BFGXP8CfHmSKPU="
